# 表示这是 compose 配置文件第三版
version: '3'

# 每个服务都是一个 Docker 容器
# 所以必须用 image 指定服务的镜像名或者从 Dockerfile 中 build 镜像
services:
  web:
    # build 指定了 Dockerfile 所在的路径
    build: .
    restart: on-failure:5
    # depends_on 设定了依赖，这里 redisdemo 会先于 pyweb 启动
    # 但是如果 redisdemo 启动时间长于 pyweb
    # 那么 pyweb 运行的时候 redisdemo 未必可用
    # mysqldemo 同理
    depends_on:
      - redisdemo
      - mysqldemo
    environment:
      - "CACHE_HOST=redisdemo"
      - "CACHE_PORT=6379"
      - "DATABASE_USERNAME=root"
      - "DATABASE_IP=mysqldemo"
      - "DATABASE=bbs"
      - "SERVER_HOST=0.0.0.0"
      - "SERVER_PORT=3000"
      - "TEST_MAIL=hldgaoshuo@163.com"
      - "ADMIN_MAIL=gaoshuo@hldgaohsuo.xyz"

  redisdemo:
    # 每个服务必须用 image 指定镜像名或者从 Dockerfile 中 build
    # 这里用 image 指定镜像，redis:alpine 是 redis 项目的官方 Docker 镜像
    image: "redis:latest"
    restart: on-failure:5

  mysqldemo:
    # 每个服务必须用 image 指定镜像名或者从 Dockerfile 中 build
    # 这里用 image 指定镜像。
    image: "mysql:5.6"
    restart: on-failure:5
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      # 数据库的连接信息
      - "MYSQL_ROOT_PASSWORD=zkuvzkqi"
